version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: csravgvstvs/upgrade-test:beta1.1
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.2"
          memory: 500M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:80"
    networks:
      - webnet
networks:
  webnet: